// <auto-generated />
namespace CampMa8.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedcampgroundName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedcampgroundName));
        
        string IMigrationMetadata.Id
        {
            get { return "202001292212055_changed campgroundName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
